import type { MenuItem, Offer, TableData, DailySpecial } from './types'

export const menuItems: MenuItem[] = [
  // BURGER
  {
    id: 'burger-1',
    category: 'burger',
    name: { de: 'Classic Burger', en: 'Classic Burger', tr: 'Klasik Burger', fr: 'Burger Classique', it: 'Burger Classico', es: 'Hamburguesa Clásica' },
    description: { de: 'Saftiges Rindfleisch, Salat, Tomate, Zwiebel, Gurke, Ketchup', en: 'Juicy beef, lettuce, tomato, onion, pickle, ketchup', tr: 'Sulu dana eti, marul, domates, soğan, turşu, ketçap', fr: 'Bœuf juteux, salade, tomate, oignon, cornichon, ketchup', it: 'Manzo succoso, lattuga, pomodoro, cipolla, cetriolino, ketchup', es: 'Carne jugosa, lechuga, tomate, cebolla, pepinillo, ketchup' },
    price: 14.90,
    image: '/images/burger-classic.jpg',
    extras: [
      { id: 'x1', name: 'Extra Käse', price: 1.50 },
      { id: 'x2', name: 'Bacon', price: 2.00 },
      { id: 'x3', name: 'Avocado', price: 2.50 },
    ],
    tags: ['popular'],
    available: true,
    calories: 620,
    allergens: ['Gluten', 'Milch', 'Ei'],
  },
  {
    id: 'burger-2',
    category: 'burger',
    name: { de: 'BBQ Burger', en: 'BBQ Burger', tr: 'BBQ Burger', fr: 'Burger BBQ', it: 'Burger BBQ', es: 'Hamburguesa BBQ' },
    description: { de: 'Rindfleisch, BBQ-Sauce, Bacon, Cheddar, Röstzwiebeln', en: 'Beef, BBQ sauce, bacon, cheddar, crispy onions', tr: 'Dana eti, BBQ sos, bacon, çedar, çıtır soğan', fr: 'Bœuf, sauce BBQ, bacon, cheddar, oignons frits', it: 'Manzo, salsa BBQ, bacon, cheddar, cipolle croccanti', es: 'Carne, salsa BBQ, bacon, cheddar, cebollas crujientes' },
    price: 17.90,
    image: '/images/burger-bbq.jpg',
    extras: [
      { id: 'x1', name: 'Extra Käse', price: 1.50 },
      { id: 'x4', name: 'Jalapeños', price: 1.00 },
    ],
    tags: ['popular', 'spicy'],
    available: true,
    calories: 780,
    allergens: ['Gluten', 'Milch'],
  },
  {
    id: 'burger-3',
    category: 'burger',
    name: { de: 'Veggie Burger', en: 'Veggie Burger', tr: 'Sebze Burger', fr: 'Burger Végétarien', it: 'Burger Veggie', es: 'Hamburguesa Vegetal' },
    description: { de: 'Hausgemachter Gemüsepatty, Avocado, Sprossen, Senf', en: 'Homemade veggie patty, avocado, sprouts, mustard', tr: 'Ev yapımı sebze köftesi, avokado, filiz, hardal', fr: 'Galette végétarienne maison, avocat, pousses, moutarde', it: 'Polpetta vegetale fatta in casa, avocado, germogli, senape', es: 'Hamburguesa vegetal casera, aguacate, brotes, mostaza' },
    price: 15.90,
    image: '/images/burger-veggie.jpg',
    extras: [
      { id: 'x3', name: 'Avocado', price: 2.50 },
      { id: 'x5', name: 'Extra Patty', price: 3.00 },
    ],
    tags: ['vegetarian', 'new'],
    available: true,
    calories: 480,
    allergens: ['Gluten', 'Senf'],
  },
  {
    id: 'burger-4',
    category: 'burger',
    name: { de: 'Smash Burger', en: 'Smash Burger', tr: 'Smash Burger', fr: 'Smash Burger', it: 'Smash Burger', es: 'Smash Burger' },
    description: { de: 'Doppeltes Rindfleisch, American Cheese, spezielle Soße', en: 'Double beef, American cheese, special sauce', tr: 'Çift dana eti, amerikan peyniri, özel sos', fr: 'Double bœuf, fromage américain, sauce spéciale', it: 'Doppio manzo, formaggio americano, salsa speciale', es: 'Carne doble, queso americano, salsa especial' },
    price: 19.90,
    image: '/images/burger-smash.jpg',
    extras: [
      { id: 'x2', name: 'Bacon', price: 2.00 },
      { id: 'x4', name: 'Jalapeños', price: 1.00 },
    ],
    tags: ['new', 'popular'],
    available: true,
    calories: 890,
    allergens: ['Gluten', 'Milch'],
  },

  // PIZZA
  {
    id: 'pizza-1',
    category: 'pizza',
    name: { de: 'Margherita', en: 'Margherita', tr: 'Margarita', fr: 'Margherita', it: 'Margherita', es: 'Margarita' },
    description: { de: 'Tomatensauce, Mozzarella, frisches Basilikum', en: 'Tomato sauce, mozzarella, fresh basil', tr: 'Domates sosu, mozzarella, taze fesleğen', fr: 'Sauce tomate, mozzarella, basilic frais', it: 'Salsa di pomodoro, mozzarella, basilico fresco', es: 'Salsa de tomate, mozzarella, albahaca fresca' },
    price: 13.90,
    image: '/images/pizza-margherita.jpg',
    extras: [
      { id: 'p1', name: 'Extra Mozzarella', price: 2.00 },
      { id: 'p2', name: 'Oliven', price: 1.50 },
    ],
    tags: ['vegetarian', 'popular'],
    available: true,
    calories: 720,
    allergens: ['Gluten', 'Milch'],
  },
  {
    id: 'pizza-2',
    category: 'pizza',
    name: { de: 'Diavola', en: 'Diavola', tr: 'Şeytan Pizza', fr: 'Diavola', it: 'Diavola', es: 'Diávola' },
    description: { de: 'Tomatensauce, Mozzarella, Salami piccante, Chili', en: 'Tomato sauce, mozzarella, spicy salami, chili', tr: 'Domates sosu, mozzarella, acı salam, biber', fr: 'Sauce tomate, mozzarella, salami épicé, piment', it: 'Salsa di pomodoro, mozzarella, salame piccante, peperoncino', es: 'Salsa de tomate, mozzarella, salami picante, chile' },
    price: 16.90,
    image: '/images/pizza-diavola.jpg',
    extras: [
      { id: 'p3', name: 'Extra Salami', price: 2.50 },
      { id: 'p4', name: 'Champignons', price: 1.50 },
    ],
    tags: ['spicy', 'popular'],
    available: true,
    calories: 840,
    allergens: ['Gluten', 'Milch'],
  },
  {
    id: 'pizza-3',
    category: 'pizza',
    name: { de: 'Quattro Stagioni', en: 'Quattro Stagioni', tr: 'Dört Mevsim', fr: 'Quatre Saisons', it: 'Quattro Stagioni', es: 'Cuatro Estaciones' },
    description: { de: 'Artischocken, Schinken, Pilze, Oliven, Mozzarella', en: 'Artichokes, ham, mushrooms, olives, mozzarella', tr: 'Enginar, jambon, mantar, zeytin, mozzarella', fr: 'Artichauts, jambon, champignons, olives, mozzarella', it: 'Carciofi, prosciutto, funghi, olive, mozzarella', es: 'Alcachofas, jamón, champiñones, aceitunas, mozzarella' },
    price: 17.90,
    image: '/images/pizza-quattro.jpg',
    extras: [
      { id: 'p1', name: 'Extra Mozzarella', price: 2.00 },
    ],
    tags: [],
    available: true,
    calories: 780,
    allergens: ['Gluten', 'Milch'],
  },
  {
    id: 'pizza-4',
    category: 'pizza',
    name: { de: 'Vegan Pizza', en: 'Vegan Pizza', tr: 'Vegan Pizza', fr: 'Pizza Vegan', it: 'Pizza Vegana', es: 'Pizza Vegana' },
    description: { de: 'Tomatensauce, veganer Käse, Gemüse der Saison', en: 'Tomato sauce, vegan cheese, seasonal vegetables', tr: 'Domates sosu, vegan peynir, mevsim sebzeleri', fr: 'Sauce tomate, fromage vegan, légumes de saison', it: 'Salsa di pomodoro, formaggio vegano, verdure di stagione', es: 'Salsa de tomate, queso vegano, verduras de temporada' },
    price: 15.90,
    image: '/images/pizza-vegan.jpg',
    extras: [],
    tags: ['vegan', 'new'],
    available: true,
    calories: 560,
    allergens: ['Gluten'],
  },

  // DRINKS
  {
    id: 'drink-1',
    category: 'drinks',
    name: { de: 'Cola', en: 'Cola', tr: 'Kola', fr: 'Coca-Cola', it: 'Coca-Cola', es: 'Coca-Cola' },
    description: { de: 'Klassische Cola, 0.5l', en: 'Classic cola, 0.5l', tr: 'Klasik kola, 0.5l', fr: 'Coca-Cola classique, 0.5l', it: 'Coca-Cola classica, 0.5l', es: 'Coca-Cola clásica, 0.5l' },
    price: 4.50,
    image: '/images/drink-cola.jpg',
    extras: [],
    tags: ['popular'],
    available: true,
    calories: 180,
  },
  {
    id: 'drink-2',
    category: 'drinks',
    name: { de: 'Mineralwasser', en: 'Mineral Water', tr: 'Maden Suyu', fr: 'Eau minérale', it: 'Acqua minerale', es: 'Agua mineral' },
    description: { de: 'Still oder sprudelnd, 0.5l', en: 'Still or sparkling, 0.5l', tr: 'Sade veya gazlı, 0.5l', fr: 'Plate ou gazeuse, 0.5l', it: 'Naturale o frizzante, 0.5l', es: 'Sin gas o con gas, 0.5l' },
    price: 3.50,
    image: '/images/drink-water.jpg',
    extras: [],
    tags: [],
    available: true,
    calories: 0,
  },
  {
    id: 'drink-3',
    category: 'drinks',
    name: { de: 'Bier vom Fass', en: 'Draft Beer', tr: 'Fıçı Bira', fr: 'Bière pression', it: 'Birra alla spina', es: 'Cerveza de barril' },
    description: { de: 'Frisch gezapftes Bier, 0.5l', en: 'Freshly tapped beer, 0.5l', tr: 'Taze çekilen bira, 0.5l', fr: 'Bière fraîche, 0.5l', it: 'Birra fresca alla spina, 0.5l', es: 'Cerveza fresca de barril, 0.5l' },
    price: 6.50,
    image: '/images/drink-beer.jpg',
    extras: [],
    tags: ['popular'],
    available: true,
    calories: 215,
  },
  {
    id: 'drink-4',
    category: 'drinks',
    name: { de: 'Frischer Orangensaft', en: 'Fresh Orange Juice', tr: 'Taze Portakal Suyu', fr: 'Jus d\'orange frais', it: 'Succo d\'arancia fresco', es: 'Zumo de naranja fresco' },
    description: { de: 'Frisch gepresst, 0.3l', en: 'Freshly squeezed, 0.3l', tr: 'Taze sıkılmış, 0.3l', fr: 'Fraîchement pressé, 0.3l', it: 'Appena spremuto, 0.3l', es: 'Recién exprimido, 0.3l' },
    price: 5.50,
    image: '/images/drink-oj.jpg',
    extras: [],
    tags: [],
    available: true,
    calories: 110,
  },
  {
    id: 'drink-5',
    category: 'drinks',
    name: { de: 'Kaffee', en: 'Coffee', tr: 'Kahve', fr: 'Café', it: 'Caffè', es: 'Café' },
    description: { de: 'Espresso, Cappuccino oder Latte – wählen Sie beim Kellner', en: 'Espresso, cappuccino or latte – ask your waiter', tr: 'Espresso, kapuçino veya latte – garsona sorun', fr: 'Espresso, cappuccino ou latte – demandez au serveur', it: 'Espresso, cappuccino o latte – chiedi al cameriere', es: 'Espresso, capuchino o latte – pregunta al camarero' },
    price: 4.00,
    image: '/images/drink-coffee.jpg',
    extras: [],
    tags: [],
    available: true,
    calories: 5,
  },

  // DESSERTS
  {
    id: 'dessert-1',
    category: 'desserts',
    name: { de: 'Tiramisu', en: 'Tiramisu', tr: 'Tiramisu', fr: 'Tiramisu', it: 'Tiramisù', es: 'Tiramisú' },
    description: { de: 'Klassisches Tiramisu mit Mascarpone', en: 'Classic tiramisu with mascarpone', tr: 'Mascarpone ile klasik tiramisu', fr: 'Tiramisu classique à la mascarpone', it: 'Tiramisù classico con mascarpone', es: 'Tiramisú clásico con mascarpone' },
    price: 8.90,
    image: '/images/dessert-tiramisu.jpg',
    extras: [],
    tags: ['popular'],
    available: true,
    calories: 380,
    allergens: ['Milch', 'Ei', 'Gluten'],
  },
  {
    id: 'dessert-2',
    category: 'desserts',
    name: { de: 'Lava Cake', en: 'Lava Cake', tr: 'Lav Kek', fr: 'Fondant au Chocolat', it: 'Tortino al Cioccolato', es: 'Coulant de Chocolate' },
    description: { de: 'Warmer Schokoladenkuchen mit flüssigem Kern', en: 'Warm chocolate cake with liquid center', tr: 'Sıcak çikolatalı kek, sıvı merkez', fr: 'Gâteau au chocolat chaud avec cœur coulant', it: 'Tortino di cioccolato caldo con cuore fondente', es: 'Pastel de chocolate caliente con centro líquido' },
    price: 9.90,
    image: '/images/dessert-lava.jpg',
    extras: [
      { id: 'd1', name: 'Vanilleeis', price: 2.50 },
    ],
    tags: ['popular', 'new'],
    available: true,
    calories: 450,
    allergens: ['Milch', 'Ei', 'Gluten'],
  },
  {
    id: 'dessert-3',
    category: 'desserts',
    name: { de: 'Sorbet', en: 'Sorbet', tr: 'Sorbe', fr: 'Sorbet', it: 'Sorbetto', es: 'Sorbete' },
    description: { de: 'Drei Kugeln: Zitrone, Mango, Erdbeer', en: 'Three scoops: lemon, mango, strawberry', tr: 'Üç top: limon, mango, çilek', fr: 'Trois boules: citron, mangue, fraise', it: 'Tre palline: limone, mango, fragola', es: 'Tres bolas: limón, mango, fresa' },
    price: 7.90,
    image: '/images/dessert-sorbet.jpg',
    extras: [],
    tags: ['vegan', 'glutenFree'],
    available: true,
    calories: 210,
  },
  {
    id: 'dessert-4',
    category: 'desserts',
    name: { de: 'Cheesecake', en: 'Cheesecake', tr: 'Cheesecake', fr: 'Cheesecake', it: 'Cheesecake', es: 'Tarta de Queso' },
    description: { de: 'New Yorker Cheesecake mit Beerenkompott', en: 'New York cheesecake with berry compote', tr: 'New York cheesecake, meyve kompostu', fr: 'Cheesecake new-yorkais avec compote de baies', it: 'Cheesecake alla New York con composta di frutti di bosco', es: 'Cheesecake de Nueva York con compota de frutos rojos' },
    price: 8.50,
    image: '/images/dessert-cheesecake.jpg',
    extras: [],
    tags: [],
    available: true,
    calories: 420,
    allergens: ['Milch', 'Ei', 'Gluten'],
  },
]

export const offers: Offer[] = [
  {
    id: 'offer-1',
    title: { de: 'Happy Hour', en: 'Happy Hour', tr: 'Mutlu Saat', fr: 'Happy Hour', it: 'Happy Hour', es: 'Happy Hour' },
    description: { de: '20% Rabatt auf alle Getränke von 15–18 Uhr', en: '20% off all drinks from 3–6pm', tr: 'Saat 15-18 arası tüm içeceklerde %20 indirim', fr: '20% de réduction sur toutes les boissons de 15h à 18h', it: '20% di sconto su tutte le bevande dalle 15 alle 18', es: '20% de descuento en bebidas de 15 a 18h' },
    discount: 20,
    discountType: 'percent',
    image: '/images/offer-happy-hour.jpg',
    validUntil: '2026-12-31',
  },
  {
    id: 'offer-2',
    title: { de: 'Familien-Deal', en: 'Family Deal', tr: 'Aile Fırsatı', fr: 'Offre Famille', it: 'Offerta Famiglia', es: 'Oferta Familiar' },
    description: { de: '4 Burger + 4 Getränke für CHF 59.–', en: '4 burgers + 4 drinks for CHF 59.–', tr: '4 burger + 4 içecek 59 CHF', fr: '4 burgers + 4 boissons pour CHF 59.–', it: '4 burger + 4 bevande per CHF 59.–', es: '4 hamburguesas + 4 bebidas por CHF 59.–' },
    discount: 59,
    discountType: 'fixed',
    image: '/images/offer-family.jpg',
    validUntil: '2026-06-30',
    code: 'FAMILY24',
  },
  {
    id: 'offer-3',
    title: { de: 'Geburtstags-Special', en: 'Birthday Special', tr: 'Doğum Günü Özel', fr: 'Spécial Anniversaire', it: 'Speciale Compleanno', es: 'Especial Cumpleaños' },
    description: { de: 'Gratis Dessert an Ihrem Geburtstag', en: 'Free dessert on your birthday', tr: 'Doğum günün bedava tatlı', fr: 'Dessert gratuit pour votre anniversaire', it: 'Dessert gratis nel giorno del tuo compleanno', es: 'Postre gratis en tu cumpleaños' },
    discount: 100,
    discountType: 'percent',
    image: '/images/offer-birthday.jpg',
    validUntil: '2026-12-31',
  },
]

export const tables: TableData[] = Array.from({ length: 12 }, (_, i) => ({
  id: `table-${i + 1}`,
  number: i + 1,
  status: i < 3 ? 'occupied' : i === 3 ? 'reserved' : 'free',
  seats: i % 3 === 0 ? 6 : i % 2 === 0 ? 4 : 2,
}))

export const dailySpecial: DailySpecial = {
  menuItemId: 'burger-4',
  note: {
    de: 'Heute empfiehlt der Küchenchef unseren neuen Smash Burger – ein echtes Geschmackserlebnis!',
    en: 'Today the chef recommends our new Smash Burger – a true taste experience!',
    tr: 'Bugün şef yeni Smash Burger\'ımızı öneriyor – gerçek bir lezzet deneyimi!',
    fr: 'Aujourd\'hui, le chef recommande notre nouveau Smash Burger – une vraie expérience gustative!',
    it: 'Oggi lo chef consiglia il nostro nuovo Smash Burger – una vera esperienza di gusto!',
    es: '¡Hoy el chef recomienda nuestra nueva Smash Burger – una verdadera experiencia gastronómica!',
  },
}
